### ISSUE TITLE
Hyper-parameters for successful DQN Agent

### ISSUE THREAD

**Issue by ichko** [marload/deep-rl-tf2#1]
Hi @marload,

Great repository you have here :smile:! I am running your DQN script and I am trying to solve `CartPole` with it (consistently get `>200` score).

I ran the script with the default parameters, but the agent is having trouble learning a successful policy.  All I get is fluctuating scores between 10 and 100 for the first 800 episodes I trained it on. There was one episode with >200 but it was early in the training and having in mind that `eps` would have been very high at this point I think this must have been due to chance.

So my question is - if you have trained a successful agent with this algorithm can you provide me with "working" parameters? Or maybe DQN is just unstable in nature and I should run the script a couple of more times and hope for something better?

I have not reviewed the code thoroughly, because I wanted to see it working first, but at first glance, it looks clean and simple.

Anyway, thanks for posting it on Reddit, not sure why it was deleted. I hope I can learn a thing or two from it since I am working on something similar at the moment. :smile: 

Have a great day!

**Comment by archsyscall** [comment]
First of all, thank you very much for your interest in this project. As you say, dqn and drqn are not working perfectly yet. I'll fix this issue in no time. If you want to participate in this project, we can do it together. Thank you very much.

**Comment by ichko** [comment]
Would love to help if I could.

**Comment by ichko** [comment]
Just started to read your code and noticed some problems. You can see my updates here: https://github.com/marload/deep-rl-tf2/compare/master...ichko:master

The main problem I noticed was that you sample from normal distribution to compare with `eps`. This leads to oversampling of random actions (I think). The right way to do it is to compare `eps` with something drawn from a uniform distribution between [0, 1]. Having it like that guarantees that the greedy actions are taken `eps%` of the time.

I did a test run after changing this and the results improved significantly. (the run in blue is the one with uniform sampling).

![image](https://user-images.githubusercontent.com/7668305/77102855-2e832380-6a22-11ea-9035-d8bac388761f.png)

The inconsistency of the results remains though :disappointed:. Will continue to work on that.

I also did some stylistic changes. Hope you don't mind :smile:.

**Comment by archsyscall** [comment]
Sorry for replying late! I made the DQN and DRQN work normally. In addition, the code style has been changed to a better architecture. Thank you for waiting!

**Comment by archsyscall** [comment]
Thx :)
