### ISSUE TITLE
"PPO_Continuous.py" trained 1000 EP without effect

### ISSUE THREAD

**Issue by Synmul** [marload/deep-rl-tf2#3]
[No changes have been made to the code. 
tensorflow version is 2.2, will this affect it?
![20200610215857](https://user-images.githubusercontent.com/50161120/84277181-b9794300-ab65-11ea-955d-01957473a201.png)

**Comment by MedhaviMonish** [comment]
Similar thing happened to me . I tried A2C continuous for pendulum without any change (except  total episode was set to 3000) but reward is still varies between -1000 to -0 , it rarely goes to  -0. So i tried A2C discrete without any change for cartpole and again it is too slow to train ..

**Comment by natetsang** [comment]
I received the same results - PPO continuous doesn't appear to learn anything. I'm running TF2.3, so it doesn't have to do with your version @Synmul

**Comment by alifrahmatullah** [comment]
Same here. No changes

**Comment by natetsang** [comment]
@Synmul did you close because it was fixed?

**Comment by Daniel-Huff** [comment]
i think maybe the author forget to use actor_loss and critic_loss to backword()
